### ISSUE TITLE
Retry failed batches

### ISSUE THREAD

**Issue by nblumhardt** [datalust/bunyan-seq#1]
Currently, batches of log events that cannot be sent to Seq for any reason will be dropped.

If the returned status code from the HTTP request indicates that the server is down (0) or unavailable (503) then some number of retries should be attempted.

**Comment by raybooysen** [comment]
Looking at the code, wouldn't this be done as part of the `seq-logging` package?

**Comment by nblumhardt** [comment]
Yes, I think that would be the case :+1:

**Comment by raybooysen** [comment]
Created an issue in seq-logging, We can close this.
