### ISSUE TITLE
Seq stream mutates event object

### ISSUE THREAD

**Issue by Spragalas** [datalust/bunyan-seq#11]
Seq stream mutates event object thus event object cannot be used in following streams because it is missing required data.
File: bunyan-seq/seq_stream.js
Lines: 49-52

I suppose these lines must be removed. Is there any good reason to delete these properties?

Reproduce:

```
var log = bunyan.createLogger({
    name: 'myapp',
    streams: [
        seq.createStream({
            serverUrl: 'http://localhost:5341',
            level: 'info'
        }),
        {
            stream: process.stdout,
            level: 'warn',
        }
    ]
});
log.info('Hi!');
```
This does not log msg: "Hi" to stdout

**Comment by nblumhardt** [comment]
Hi! Thanks for the note, we should definitely fix this :+1: 

The reasons for approaching it this way are unfortunately lost - the properties are deleted so that they're not duplicated in Seq, but we should do this by copying the event fields into the object that is serialized for Seq.

**Comment by Spragalas** [comment]
Hi. I have fixed the problem for you :)
Thanks for clarification
