### ISSUE TITLE
why is npm a primary dependancy?

### ISSUE THREAD

**Issue by ngbrown** [datalust/bunyan-seq#13]
When depending on this package, it seems to be pulling in `npm` since it's listed as a dependency.  It was added in commit dbc2241e3d2d3b0ccd352150ae403260c7c9ef38.

If it really is needed for the `mocha` package, then it should be in the `devDependencies` section.  That way it won't be pulled in on packages that are just using `bunyan-seq`.

**Comment by nblumhardt** [comment]
Ah, thanks Nathan, I think that was accidentally committed along with the other change. I'll PR up a fix!

Nick
