### ISSUE TITLE
onError doesn't properly handle errors

### ISSUE THREAD

**Issue by Artaud** [datalust/bunyan-seq#24]
This issue has crashed my server and set me back a few hours.

The function you pass into `onError` property of SeqConfig (createStream method argument) gets called on an error, but at the same time another error is being emitted by the SeqStream which is not handled.

To alleviate that, you need to setup your logger as follows:

````
const streams = []
const seqStream = bunyanSeq.createStream({
    serverUrl: 'http://X.Y.Z.W',
    level: 'info',
    apiKey: 'ABCDE',
    onError: (e: Error) => { 
        console.trace('Logging failed:', e);
   }
})

seqStream.stream.on('error', (e) => console.trace('Now this is what I call error!',e)) // This is the important line
streams.push(seqStream)

let log: any = bunyan.createLogger({
  name: 'myAwesomeLogger',
  streams: streams
})

````

If you don't do that, any error that arises from stream misconfiguration or (as happened to me) from an outage of the logging server, will crash your app.

**Comment by larenelg** [comment]
@Artaud — thanks for raising this issue! Apologies that it set you back.

I'll try to reproduce this behaviour, and look into how we can push that as default behaviour down into the app.

**Comment by Artaud** [comment]
Many thanks for the fast reply and for looking into it!

To reproduce, just set up the stream with an invalid apikey or serverUrl, which will in turn raise two errors of the same kind (HTTP log shipping failed 403 - see https://github.com/datalust/seq-logging/blob/766fe1fa556668cb261076b53cafc674f1e67810/seq_logger.js#L285)

**Comment by larenelg** [comment]
Hi @Artaud, thank you! I've found what's wrong, we're calling `this.destroy()` on every error event emitted by SeqStream... which crashes the parent app 😢

If you don't mind reviewing https://github.com/datalust/bunyan-seq/pull/25

You will no longer need the extra line,
`seqStream.stream.on('error', (e) => console.trace('Now this is what I call error!',e)) // This is the important line`
after this is merged.
