### ISSUE TITLE
Typescript error when building application

### ISSUE THREAD

**Issue by tavo2k4** [datalust/bunyan-seq#28]
I get a TS build error with index.d.ts file in library. "npm run build" command

"index.d.ts:11:12 - error TS2503: Cannot find namespace 'config'."
"level: config.level;"

I resolved by adding a "// @ts-nocheck" at the top of file. Do you have or working on a better solution? Can you add this temp fix to library in Git?

**Comment by larenelg** [comment]
Hi @tavo2k4 - thanks for that. That should be a `string` type! I'll PR up a fix as soon as I can.

**Comment by larenelg** [comment]
Hi @tavo2k4 — you should be able to update to `bunyan-seq@0.7.0` and take away @ts-nocheck now!
