### ISSUE TITLE
Electron - Uglify Issues

### ISSUE THREAD

**Issue by raybooysen** [datalust/bunyan-seq#5]
Hi there

We're using bunyan and bunyan-seq in an electron renderer process (a Chromium browser window).  Since this is electron, we are able to access node APIs.  However, to reduce bundle sizes, we are Ugilfying.

However, we're tripped up in this library as it, and rightfully so, uses ES6 constructs like `let`.  This means that UgilfyJS doesn't work as it doesn't support ES6 yet.

I was wondering if anyone had some ideas, I'm not convinced this library should change because of other tool's deficiencies.

**Comment by raybooysen** [comment]
Saying that, this is opening a can of worms.  this library uses seq-logging, which again, rightfully so, uses ES6 constructs.  Closing.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. It'd be interesting to hear where you land - I haven't tried uglifying ES6 directly yet, would an intermediate transpilation step using something like Babel work for you? Cheers!

**Comment by raybooysen** [comment]
Hi @nblumhardt 

The way I've solved this is, because we're a TS project, I just include my node_modules in the compilation step and ask TS to output es5.  That means that the bunyan-seq code is transpiled. 

Not ideal but works really well.

**Comment by nblumhardt** [comment]
Great - thanks :+1:
