### ISSUE TITLE
Error in Shipping Stops all logging

### ISSUE THREAD

**Issue by raybooysen** [datalust/bunyan-seq#6]
If for any reason an error occurs while shipping, all logging stops happening.  This is because bunyan-seq, when constructing the logger, emits an 'error' event on the EventEmitter.  If there are no subscribers to this by default, it just throws.  Which stops everything else working. 

```
loggerConfig.onError = (e) => {
            this.emit('error', e);
            onError(e);
        };        
```

**Comment by nblumhardt** [comment]
Thanks for the report, will check this one out.

**Comment by nblumhardt** [comment]
0.1.5 is now published with the fix for this. Thanks Ray!

**Comment by raybooysen** [comment]
Works great, thanks
